### ISSUE TITLE
Slowing down

### ISSUE THREAD

**Issue by FuzzySadist** [mcdamo/tab-image-saver#54] opened 2020-02-21 07:31 UTC
I've been downloading a ton of images, and I'm noticing occasionally the extension slows way down... where I click on 'download' and 5-6 seconds pass before I can click it again.  The files are only about 5mb, there are no other active downloads... not sure what's causing the slow down.  In addition, it doesn't happen consistently... same site, other times, works just fine.

**Comment by mcdamo** [comment] 2021-07-03 13:36
Possible Duplicate of #71

**Closed by mcdamo** 2021-07-03 13:36 UTC
