### ISSUE TITLE
Request: allow user to select any path

### ISSUE THREAD

**Issue by Jackie78De** [mcdamo/tab-image-saver#40] opened 2019-02-05 17:24 UTC
Hello, I love this addon, but I would like to have the possibility to save images anywhere on my PC, by giving a drive and folder name (c:\test\images) or a UNC-path (\\myserver\test\images) instead of saving to the download folder. Any way this can be done? Many thanks!

**Comment by mcdamo** [comment] 2019-02-06 00:33
Duplicate of #1

**Closed by mcdamo** 2019-02-06 00:33 UTC
Labels: duplicate
