### ISSUE TITLE
Versions published after 4.4.0 doesn't work

### ISSUE THREAD

**Issue by 007fjb** [mcdamo/tab-image-saver#95] opened 2024-04-13 07:06 UTC
I hadn't use your extension for a few days, but Version 4.5.1 doesn't work with me.
The image is not download, a zero appeared on the icon (which is consistent with the image not downloaded, but...) and the downloading history just says "Failure" ("échec" in French, which means failure, but maybe it's not the exact word you would get in English)
I've tried to check the debugger and its various tabs, but found nothing looking like an error message.
Getting version 4.5.0 didn't change anything, but Version 4.4.0 still works.

Thanks in advance.

**Comment by mcdamo** [comment] 2024-04-13 07:17
Duplicate of #94.

If you toggle the addon Sidebar, and try to download using the buttons in the Sidebar, does it show why it fails?

**Comment by 007fjb** [comment] 2024-04-21 09:38
Strangely enough I reinstall 4.5.3 (which I have already done after testing older versions) for the test, it worked with the sidebar and now it also works without it.I'm baffled...

    Le samedi 13 avril 2024 à 09:18:18 UTC+2, mcdamo ***@***.***> a écrit :  
 
 


Duplicate of #94.

If you toggle the addon Sidebar, and try to download using the buttons in the Sidebar, does it show why it fails?

**Closed** 2024-08-30 12:55 UTC
Labels: duplicate
